/**
 * Auto-generated view order configuration from Keystone models
 * This file is generated by view-order/generate-view-order.ts
 * DO NOT EDIT THIS FILE MANUALLY
 */

/**
 * View order configuration for the Keystone application
 * This defines the order of field types that correspond to view indices
 */
export const VIEW_ORDER = [
  "text",
  "password",
  "relationship",
  "timestamp",
  "checkbox",
  "integer",
  "select",
  "decimal"
];